"""initial versioned channel service and tenant control plane

Revision ID: 20260825_0001
Revises:
Create Date: 2026-08-25 02:34:32.064160
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260825_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_packs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=128), nullable=False),
        sa.Column("channel_handle", sa.String(length=255), nullable=False),
        sa.Column("resolved_channel_id", sa.String(length=255), nullable=True),
        sa.Column("resolved_channel_name", sa.String(length=255), nullable=True),
        sa.Column("total_purchased_video_count", sa.Integer(), nullable=False),
        sa.Column("ready_video_count", sa.Integer(), nullable=False),
        sa.Column("batch_count", sa.Integer(), nullable=False),
        sa.Column("manifest_json", sa.JSON(), nullable=True),
        sa.Column("export_paths_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel_quotes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=128), nullable=False),
        sa.Column("channel_handle", sa.String(length=255), nullable=False),
        sa.Column("resolved_channel_id", sa.String(length=255), nullable=True),
        sa.Column("resolved_channel_name", sa.String(length=255), nullable=True),
        sa.Column("requested_max_videos", sa.Integer(), nullable=False),
        sa.Column("included_video_count", sa.Integer(), nullable=False),
        sa.Column("excluded_video_count", sa.Integer(), nullable=False),
        sa.Column("current_batch_index", sa.Integer(), nullable=False),
        sa.Column("current_batch_video_count", sa.Integer(), nullable=False),
        sa.Column("current_batch_amount_cents", sa.Integer(), nullable=False),
        sa.Column("total_included_amount_cents", sa.Integer(), nullable=False),
        sa.Column("per_video_cents", sa.Integer(), nullable=False),
        sa.Column("estimated_ready_minutes", sa.Integer(), nullable=False),
        sa.Column("eta_confidence", sa.String(length=32), nullable=False),
        sa.Column("recommended_starter_batch_size", sa.Integer(), nullable=False),
        sa.Column("planning_latency_ms", sa.Integer(), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("batch_plan_json", sa.JSON(), nullable=False),
        sa.Column("price_breakdown_json", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "checkout_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("total_amount_cents", sa.Integer(), nullable=False),
        sa.Column("quote_ids_json", sa.JSON(), nullable=False),
        sa.Column("line_items_json", sa.JSON(), nullable=False),
        sa.Column("payment_provider", sa.String(length=64), nullable=False),
        sa.Column("payment_status", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checkout_sessions_idempotency_key"),
        "checkout_sessions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "egress_pools",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("pool_kind", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("health_group", sa.String(length=128), nullable=True),
        sa.Column("concurrency_limit", sa.Integer(), nullable=False),
        sa.Column("last_error_kind", sa.String(length=64), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_rate_limited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_rate_limit_count", sa.Integer(), nullable=False),
        sa.Column("quarantine_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_canary_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_canary_finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_canary_status", sa.String(length=32), nullable=True),
        sa.Column("last_canary_error_kind", sa.String(length=64), nullable=True),
        sa.Column("last_canary_error_detail", sa.Text(), nullable=True),
        sa.Column("last_canary_video_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_egress_pools_health_group"), "egress_pools", ["health_group"], unique=False
    )
    op.create_table(
        "offering_readiness_overrides",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("publication_state", sa.String(length=32), nullable=True),
        sa.Column("acceptance_scope", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "offering_readiness_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("publication_state", sa.String(length=32), nullable=False),
        sa.Column("acceptance_scope", sa.String(length=32), nullable=False),
        sa.Column("capacity_score", sa.Integer(), nullable=False),
        sa.Column("purchasable", sa.Boolean(), nullable=False),
        sa.Column("hard_stop_reasons_json", sa.JSON(), nullable=False),
        sa.Column("soft_warning_reasons_json", sa.JSON(), nullable=False),
        sa.Column("healthy_pool_group_count", sa.Integer(), nullable=False),
        sa.Column("queue_headroom_percent", sa.Float(), nullable=False),
        sa.Column("latest_catalog_canary_status", sa.String(length=32), nullable=True),
        sa.Column("latest_arbitrary_canary_status", sa.String(length=32), nullable=True),
        sa.Column("latest_soak_status", sa.String(length=32), nullable=True),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("source_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduler_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("probe_key", sa.String(length=255), nullable=False),
        sa.Column("pool_id", sa.String(length=64), nullable=True),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_kind", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduler_attempts_job_id"), "scheduler_attempts", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduler_attempts_pool_id"), "scheduler_attempts", ["pool_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduler_attempts_probe_key"), "scheduler_attempts", ["probe_key"], unique=False
    )
    op.create_table(
        "scheduler_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("probe_key", sa.String(length=255), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("channel_handle", sa.String(length=255), nullable=True),
        sa.Column("lane", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("subscriber_count", sa.Integer(), nullable=False),
        sa.Column("assigned_pool_id", sa.String(length=64), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_kind", sa.String(length=64), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduler_jobs_assigned_pool_id"),
        "scheduler_jobs",
        ["assigned_pool_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduler_jobs_channel_handle"),
        "scheduler_jobs",
        ["channel_handle"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduler_jobs_probe_key"), "scheduler_jobs", ["probe_key"], unique=True
    )
    op.create_index(
        op.f("ix_scheduler_jobs_video_id"), "scheduler_jobs", ["video_id"], unique=False
    )
    op.create_table(
        "soak_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requested_jobs", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_soak_runs_status"), "soak_runs", ["status"], unique=False)
    op.create_table(
        "source_channels",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("handle", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "external_id", name="uq_source_channels_platform_external"
        ),
    )
    op.create_index(op.f("ix_source_channels_handle"), "source_channels", ["handle"], unique=False)
    op.create_index(
        op.f("ix_source_channels_platform"), "source_channels", ["platform"], unique=False
    )
    op.create_table(
        "synthetic_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("channel_handle", sa.String(length=255), nullable=True),
        sa.Column("namespace", sa.String(length=128), nullable=True),
        sa.Column("mode", sa.String(length=64), nullable=True),
        sa.Column("max_videos", sa.Integer(), nullable=True),
        sa.Column("published_after", sa.String(length=32), nullable=True),
        sa.Column("published_before", sa.String(length=32), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_synthetic_runs_channel_handle"),
        "synthetic_runs",
        ["channel_handle"],
        unique=False,
    )
    op.create_index(
        op.f("ix_synthetic_runs_run_kind"), "synthetic_runs", ["run_kind"], unique=False
    )
    op.create_index(op.f("ix_synthetic_runs_status"), "synthetic_runs", ["status"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    op.create_table(
        "transcript_probes",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("video_url", sa.Text(), nullable=False),
        sa.Column("channel_handle", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("prefer_auto", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("transcript_source", sa.String(length=64), nullable=True),
        sa.Column("artifact_path", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_transcript_probes_video_id"), "transcript_probes", ["video_id"], unique=False
    )
    op.create_table(
        "user_accounts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("auth_provider", sa.String(length=64), nullable=False),
        sa.Column("auth_subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "auth_provider", "auth_subject", name="uq_user_accounts_provider_subject"
        ),
    )
    op.create_index(op.f("ix_user_accounts_status"), "user_accounts", ["status"], unique=False)
    op.create_table(
        "entitlements",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("pack_id", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["channel_packs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entitlements_pack_id"), "entitlements", ["pack_id"], unique=False)
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=True),
        sa.Column("job_kind", sa.String(length=64), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_key", sa.String(length=255), nullable=False),
        sa.Column("pipeline_version", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["source_channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_channel_id"), "ingestion_jobs", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_dedupe_key"), "ingestion_jobs", ["dedupe_key"], unique=True
    )
    op.create_index(
        op.f("ix_ingestion_jobs_job_kind"), "ingestion_jobs", ["job_kind"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_lease_expires_at"),
        "ingestion_jobs",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_lease_owner"), "ingestion_jobs", ["lease_owner"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_next_run_at"), "ingestion_jobs", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_source_kind"), "ingestion_jobs", ["source_kind"], unique=False
    )
    op.create_index(op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False)
    op.create_table(
        "pack_batches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("pack_id", sa.String(length=64), nullable=False),
        sa.Column("quote_id", sa.String(length=64), nullable=False),
        sa.Column("checkout_session_id", sa.String(length=64), nullable=False),
        sa.Column("batch_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("billable_video_count", sa.Integer(), nullable=False),
        sa.Column("ready_video_count", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("estimated_ready_minutes", sa.Integer(), nullable=False),
        sa.Column("build_notes_json", sa.JSON(), nullable=False),
        sa.Column("manifest_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkout_session_id"],
            ["checkout_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["channel_packs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["channel_quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pack_batches_checkout_session_id"),
        "pack_batches",
        ["checkout_session_id"],
        unique=False,
    )
    op.create_index(op.f("ix_pack_batches_pack_id"), "pack_batches", ["pack_id"], unique=False)
    op.create_index(op.f("ix_pack_batches_quote_id"), "pack_batches", ["quote_id"], unique=False)
    op.create_table(
        "quote_videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("batch_index", sa.Integer(), nullable=False),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("channel_name", sa.String(length=255), nullable=True),
        sa.Column("channel_handle", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.String(length=32), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("video_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("transcript_source", sa.String(length=64), nullable=True),
        sa.Column("indexed_parent_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["channel_quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quote_videos_quote_id"), "quote_videos", ["quote_id"], unique=False)
    op.create_index(op.f("ix_quote_videos_video_id"), "quote_videos", ["video_id"], unique=False)
    op.create_table(
        "soak_samples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("soak_run_id", sa.String(length=64), nullable=False),
        sa.Column("sample_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["soak_run_id"],
            ["soak_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_soak_samples_soak_run_id"), "soak_samples", ["soak_run_id"], unique=False
    )
    op.create_table(
        "synthetic_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("synthetic_run_id", sa.String(length=64), nullable=False),
        sa.Column("step_name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["synthetic_run_id"],
            ["synthetic_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_synthetic_steps_synthetic_run_id"),
        "synthetic_steps",
        ["synthetic_run_id"],
        unique=False,
    )
    op.create_table(
        "tenant_channel_entitlements",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("granted_by_user_id", sa.String(length=64), nullable=True),
        sa.Column("access_level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["source_channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "channel_id", name="uq_tenant_channel_entitlements_scope"
        ),
    )
    op.create_index(
        op.f("ix_tenant_channel_entitlements_channel_id"),
        "tenant_channel_entitlements",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tenant_channel_entitlements_granted_by_user_id"),
        "tenant_channel_entitlements",
        ["granted_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tenant_channel_entitlements_status"),
        "tenant_channel_entitlements",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tenant_channel_entitlements_tenant_id"),
        "tenant_channel_entitlements",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_tenant_memberships_tenant_user"),
    )
    op.create_index(
        op.f("ix_tenant_memberships_status"), "tenant_memberships", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_memberships_tenant_id"), "tenant_memberships", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_memberships_user_id"), "tenant_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "channel_orders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("quote_id", sa.String(length=64), nullable=False),
        sa.Column("checkout_session_id", sa.String(length=64), nullable=False),
        sa.Column("pack_id", sa.String(length=64), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payment_status", sa.String(length=64), nullable=False),
        sa.Column("payment_provider", sa.String(length=64), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("notes_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["pack_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["checkout_session_id"],
            ["checkout_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["channel_packs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["channel_quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_orders_batch_id"), "channel_orders", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_channel_orders_checkout_session_id"),
        "channel_orders",
        ["checkout_session_id"],
        unique=False,
    )
    op.create_index(op.f("ix_channel_orders_pack_id"), "channel_orders", ["pack_id"], unique=False)
    op.create_index(
        op.f("ix_channel_orders_quote_id"), "channel_orders", ["quote_id"], unique=False
    )
    op.create_table(
        "ingestion_effects",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("effect_kind", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider_effect_id", sa.String(length=255), nullable=True),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "idempotency_key", name="uq_ingestion_effects_provider_idempotency"
        ),
        sa.UniqueConstraint(
            "provider", "provider_effect_id", name="uq_ingestion_effects_provider_effect"
        ),
    )
    op.create_index(
        op.f("ix_ingestion_effects_job_id"), "ingestion_effects", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_effects_provider"), "ingestion_effects", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_effects_status"), "ingestion_effects", ["status"], unique=False
    )
    op.create_table(
        "ingestion_requests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=64), nullable=True),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_ingestion_requests_tenant_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_ingestion_requests_job_id"), "ingestion_requests", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_requests_requested_by_user_id"),
        "ingestion_requests",
        ["requested_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_requests_status"), "ingestion_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_requests_tenant_id"), "ingestion_requests", ["tenant_id"], unique=False
    )
    op.create_table(
        "pack_videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pack_id", sa.String(length=64), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("quote_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("channel_name", sa.String(length=255), nullable=True),
        sa.Column("channel_handle", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.String(length=32), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("video_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("transcript_source", sa.String(length=64), nullable=True),
        sa.Column("indexed_parent_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["pack_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["channel_packs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["channel_quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pack_videos_batch_id"), "pack_videos", ["batch_id"], unique=False)
    op.create_index(op.f("ix_pack_videos_pack_id"), "pack_videos", ["pack_id"], unique=False)
    op.create_index(op.f("ix_pack_videos_quote_id"), "pack_videos", ["quote_id"], unique=False)
    op.create_index(op.f("ix_pack_videos_video_id"), "pack_videos", ["video_id"], unique=False)
    op.create_table(
        "acp_job_bridges",
        sa.Column("acp_job_id", sa.String(length=128), nullable=False),
        sa.Column("offering_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("quote_id", sa.String(length=64), nullable=True),
        sa.Column("checkout_session_id", sa.String(length=64), nullable=True),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("pack_id", sa.String(length=64), nullable=True),
        sa.Column("fixed_price_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("payment_provider", sa.String(length=64), nullable=False),
        sa.Column("payment_status", sa.String(length=64), nullable=False),
        sa.Column("buyer_subject_type", sa.String(length=64), nullable=True),
        sa.Column("buyer_subject_id", sa.String(length=255), nullable=True),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("delivery_json", sa.JSON(), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkout_session_id"],
            ["checkout_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["channel_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["channel_packs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["channel_quotes.id"],
        ),
        sa.PrimaryKeyConstraint("acp_job_id"),
    )
    op.create_index(
        op.f("ix_acp_job_bridges_checkout_session_id"),
        "acp_job_bridges",
        ["checkout_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_acp_job_bridges_offering_id"), "acp_job_bridges", ["offering_id"], unique=False
    )
    op.create_index(
        op.f("ix_acp_job_bridges_order_id"), "acp_job_bridges", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_acp_job_bridges_pack_id"), "acp_job_bridges", ["pack_id"], unique=False
    )
    op.create_index(
        op.f("ix_acp_job_bridges_quote_id"), "acp_job_bridges", ["quote_id"], unique=False
    )
    op.create_table(
        "payment_receipts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("checkout_session_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("receipt_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkout_session_id"],
            ["checkout_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["channel_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_receipts_checkout_session_id"),
        "payment_receipts",
        ["checkout_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_receipts_order_id"), "payment_receipts", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_receipts_order_id"), table_name="payment_receipts")
    op.drop_index(op.f("ix_payment_receipts_checkout_session_id"), table_name="payment_receipts")
    op.drop_table("payment_receipts")
    op.drop_index(op.f("ix_acp_job_bridges_quote_id"), table_name="acp_job_bridges")
    op.drop_index(op.f("ix_acp_job_bridges_pack_id"), table_name="acp_job_bridges")
    op.drop_index(op.f("ix_acp_job_bridges_order_id"), table_name="acp_job_bridges")
    op.drop_index(op.f("ix_acp_job_bridges_offering_id"), table_name="acp_job_bridges")
    op.drop_index(op.f("ix_acp_job_bridges_checkout_session_id"), table_name="acp_job_bridges")
    op.drop_table("acp_job_bridges")
    op.drop_index(op.f("ix_pack_videos_video_id"), table_name="pack_videos")
    op.drop_index(op.f("ix_pack_videos_quote_id"), table_name="pack_videos")
    op.drop_index(op.f("ix_pack_videos_pack_id"), table_name="pack_videos")
    op.drop_index(op.f("ix_pack_videos_batch_id"), table_name="pack_videos")
    op.drop_table("pack_videos")
    op.drop_index(op.f("ix_ingestion_requests_tenant_id"), table_name="ingestion_requests")
    op.drop_index(op.f("ix_ingestion_requests_status"), table_name="ingestion_requests")
    op.drop_index(
        op.f("ix_ingestion_requests_requested_by_user_id"), table_name="ingestion_requests"
    )
    op.drop_index(op.f("ix_ingestion_requests_job_id"), table_name="ingestion_requests")
    op.drop_table("ingestion_requests")
    op.drop_index(op.f("ix_ingestion_effects_status"), table_name="ingestion_effects")
    op.drop_index(op.f("ix_ingestion_effects_provider"), table_name="ingestion_effects")
    op.drop_index(op.f("ix_ingestion_effects_job_id"), table_name="ingestion_effects")
    op.drop_table("ingestion_effects")
    op.drop_index(op.f("ix_channel_orders_quote_id"), table_name="channel_orders")
    op.drop_index(op.f("ix_channel_orders_pack_id"), table_name="channel_orders")
    op.drop_index(op.f("ix_channel_orders_checkout_session_id"), table_name="channel_orders")
    op.drop_index(op.f("ix_channel_orders_batch_id"), table_name="channel_orders")
    op.drop_table("channel_orders")
    op.drop_index(op.f("ix_tenant_memberships_user_id"), table_name="tenant_memberships")
    op.drop_index(op.f("ix_tenant_memberships_tenant_id"), table_name="tenant_memberships")
    op.drop_index(op.f("ix_tenant_memberships_status"), table_name="tenant_memberships")
    op.drop_table("tenant_memberships")
    op.drop_index(
        op.f("ix_tenant_channel_entitlements_tenant_id"), table_name="tenant_channel_entitlements"
    )
    op.drop_index(
        op.f("ix_tenant_channel_entitlements_status"), table_name="tenant_channel_entitlements"
    )
    op.drop_index(
        op.f("ix_tenant_channel_entitlements_granted_by_user_id"),
        table_name="tenant_channel_entitlements",
    )
    op.drop_index(
        op.f("ix_tenant_channel_entitlements_channel_id"), table_name="tenant_channel_entitlements"
    )
    op.drop_table("tenant_channel_entitlements")
    op.drop_index(op.f("ix_synthetic_steps_synthetic_run_id"), table_name="synthetic_steps")
    op.drop_table("synthetic_steps")
    op.drop_index(op.f("ix_soak_samples_soak_run_id"), table_name="soak_samples")
    op.drop_table("soak_samples")
    op.drop_index(op.f("ix_quote_videos_video_id"), table_name="quote_videos")
    op.drop_index(op.f("ix_quote_videos_quote_id"), table_name="quote_videos")
    op.drop_table("quote_videos")
    op.drop_index(op.f("ix_pack_batches_quote_id"), table_name="pack_batches")
    op.drop_index(op.f("ix_pack_batches_pack_id"), table_name="pack_batches")
    op.drop_index(op.f("ix_pack_batches_checkout_session_id"), table_name="pack_batches")
    op.drop_table("pack_batches")
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_source_kind"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_next_run_at"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_lease_owner"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_lease_expires_at"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_job_kind"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_dedupe_key"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_channel_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index(op.f("ix_entitlements_pack_id"), table_name="entitlements")
    op.drop_table("entitlements")
    op.drop_index(op.f("ix_user_accounts_status"), table_name="user_accounts")
    op.drop_table("user_accounts")
    op.drop_index(op.f("ix_transcript_probes_video_id"), table_name="transcript_probes")
    op.drop_table("transcript_probes")
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_synthetic_runs_status"), table_name="synthetic_runs")
    op.drop_index(op.f("ix_synthetic_runs_run_kind"), table_name="synthetic_runs")
    op.drop_index(op.f("ix_synthetic_runs_channel_handle"), table_name="synthetic_runs")
    op.drop_table("synthetic_runs")
    op.drop_index(op.f("ix_source_channels_platform"), table_name="source_channels")
    op.drop_index(op.f("ix_source_channels_handle"), table_name="source_channels")
    op.drop_table("source_channels")
    op.drop_index(op.f("ix_soak_runs_status"), table_name="soak_runs")
    op.drop_table("soak_runs")
    op.drop_index(op.f("ix_scheduler_jobs_video_id"), table_name="scheduler_jobs")
    op.drop_index(op.f("ix_scheduler_jobs_probe_key"), table_name="scheduler_jobs")
    op.drop_index(op.f("ix_scheduler_jobs_channel_handle"), table_name="scheduler_jobs")
    op.drop_index(op.f("ix_scheduler_jobs_assigned_pool_id"), table_name="scheduler_jobs")
    op.drop_table("scheduler_jobs")
    op.drop_index(op.f("ix_scheduler_attempts_probe_key"), table_name="scheduler_attempts")
    op.drop_index(op.f("ix_scheduler_attempts_pool_id"), table_name="scheduler_attempts")
    op.drop_index(op.f("ix_scheduler_attempts_job_id"), table_name="scheduler_attempts")
    op.drop_table("scheduler_attempts")
    op.drop_table("offering_readiness_snapshots")
    op.drop_table("offering_readiness_overrides")
    op.drop_index(op.f("ix_egress_pools_health_group"), table_name="egress_pools")
    op.drop_table("egress_pools")
    op.drop_index(op.f("ix_checkout_sessions_idempotency_key"), table_name="checkout_sessions")
    op.drop_table("checkout_sessions")
    op.drop_table("channel_quotes")
    op.drop_table("channel_packs")
    # ### end Alembic commands ###
